// <auto-generated />
namespace BELibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addLinkAvatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLinkAvatar));
        
        string IMigrationMetadata.Id
        {
            get { return "202205240844124_add-LinkAvatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
